# base image
image: "ruby:2.4.1"

# build stages
stages:
  - test

# cache gems in between builds
cache:
  paths:
    - vendor/ruby

# this is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - gem install bundler -v 1.13.7 --no-ri --no-rdoc    # bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # install dependencies into ./vendor/ruby

# jobs
rspec:
  stage: test
  script:
    - bundle exec rspec -p
    - bundle exec codeclimate-test-reporter

rubocop:
  stage: test
  services: []
  before_script:
    - gem install rubocop
  script:
    - rubocop
