inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/ruby/**/*
    - tamashii.gemspec
    - bin/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
